### ISSUE TITLE
can not set metadata for S3 operations

### ISSUE THREAD

**Issue by xiuliren** [JuliaCloud/AWSSDK.jl#10]
according to the example in documentation, this should be implemented as follows:

```julia
using AWSSDK.S3
arguments = ["Bucket"=>"mybucket", "Key"=>"mykey", "Body"=>rand(UInt8, 12), "Metadata" => ["ContentEncoding"=>"gzip"]]
S3.put_object(arguments)
```
this implementation do not work. I have tried some variations, did not find the correct way to do it. 
using keyword style also do not work.

```julia
S3.put_object(Bucket="mybucket", Key="mykey", Body=rand(UInt8,12), Content-Encoding="gzip")
```
the `-` in `Content-Encoding` was parsed as a julia operation! Maybe we should change the keyword name removing the `-`? @samoconnor

**Comment by samoconnor** [comment]
I agree that the generated documentation is unclear.

I've made a small change to support passing headers to the `AWSSDK.S3` functions: https://github.com/JuliaCloud/AWSCore.jl/commit/0990b855e6189df40d5f1ff9b83925fd7d3f8e19

This now works:
```julia
julia> using AWSSDK.S3.put_object

julia> put_object([
    "Bucket" => "http.jl.test",
    "Key" => "foo",
    "Body" => rand(UInt8, 12),
    "x-amz-meta-foo" => "bar",
    "headers" => ["Content-Encoding" => "gzip"]
])
```

_Related: https://github.com/samoconnor/AWSS3.jl/issues/16#issuecomment-342380376_

**Comment by samoconnor** [comment]
> the - in Content-Encoding was parsed as a julia operation! 

Yes, the kw arguments form of the function only works when the arguments are also valid Julia argument names.

> Maybe we should change the keyword name removing the -?

There is not really any opportunity to "change" the name. It exists only in the documentation. If the S3 service expects "Content-Encoding", then we can't send "ContentEncoding".

AWSSDK.S3 is a thin low-level wrapper for the REST service. If you need convenience functions/names use https://github.com/samoconnor/AWSS3.jl.

**Comment by samoconnor** [comment]
This change in the generator marks annotates arguments that must be passes as headers: https://github.com/JuliaCloud/AWSCore.jl/commit/6ccbadcd6bc6b2ce84c2ca06c387d3489f324876

e.g. https://github.com/JuliaCloud/AWSSDK.jl/commit/aa2c1d7c62f3ce5cbe8f8e6dcb6cb5a5ac707a55#diff-a83476a5c66cc7c6bab360aee646dbb9R210

This needs to me taken further to generate documentation about the `headers=` option.

The issue also remains that the generated example does not match the required argument names:

```
[
    "Body" => "filetoupload",
    "Bucket" => "examplebucket",
    "Key" => "exampleobject",
    "Metadata" => [
        "metadata1" => "value1",
        "metadata2" => "value2"
    ]
]
```

**Comment by samoconnor** [comment]
Explanation:
The underlying issue here is a difference in the approach AWSSDK takes compared to boto3 and the AWS JS SDK.

The AWS REST and HTTP Query APIs use certain names and types for their inputs and outputs.
Boto3, AWS JS SDK etc use a different set of names and types for the inputs and outputs used in their library functions. They use the data in the service description JSON files to translate to/from the native HTTP names / types.

AWSSDK.jl tries to remove the need for the data translation layer by generating documentation that describes how to pass the native HTTP arguments directly. There are some corner cases where this isn't working.

**Comment by xiuliren** [comment]
thanks for adding this capability!
