### ISSUE TITLE
Route53 HTTP Endpoint seems to be wrong

### ISSUE THREAD

**Issue by oconnore** [JuliaCloud/AWSSDK.jl#13]
The AWS CLI tool submits requests to:
`host:route53.amazonaws.com`

The Julia SDK submits requests to:
```
julia> AWSSDK.Route53.list_hosted_zones(g)             
ERROR: DNSError: route53.us-east-1.amazonaws.com, unkno
wn node or service (EAI_NONAME) 
```

**Comment by mattBrzezinski** [comment]
The root of this issue is in `AWSCore.jl`, I've logged an issue for it [here](https://github.com/JuliaCloud/AWSCore.jl/issues/107).

Closing this issue here for the one above.
