### ISSUE TITLE
403 Errors on AWS Batch requests.

### ISSUE THREAD

**Issue by rofinn** [JuliaCloud/AWSSDK.jl#3]
It appears that something has changed with the AWS Batch API and is now returning 403s when making requests through AWSSDK.

```julia
ERROR: 403 -- The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

This only seems to occur for the batch service and tests were previously working a few days ago. I can also confirm that the same batch calls with awscli work with the same credentials.

**Comment by samoconnor** [comment]
Confirmed
```julia
julia> AWSSDK.Batch.describe_compute_environments()
ERROR: 403 -- The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
HTTP.StatusError: received a '403 - Forbidden' status in response
```
I'll check it out...

**Comment by rofinn** [comment]
Awesome, thank you. If you don't find anything obvious I could try looking at the raw http traffic.

**Comment by samoconnor** [comment]
See https://github.com/JuliaWeb/HTTP.jl/issues/112

Does this patch resolve the issue for you?
```patch
--- a/src/AWSCore.jl
+++ b/src/AWSCore.jl
@@ -399,6 +399,7 @@ function do_request(r::AWSRequest)
         end
         r[:headers]["User-Agent"] = "AWSCore.jl/0.0.0"
         r[:headers]["Host"]       = HTTP.URIs.host(HTTP.URI(r[:url]))
+        r[:headers]["Host"]       = split(r[:headers]["Host"], ":")[1]

         # Load local system credentials if needed...
         if !haskey(r, :creds) || r[:creds].token == "ExpiredToken"
```

**Comment by samoconnor** [comment]
See this commit: https://github.com/JuliaCloud/AWSCore.jl/commit/6819eef0bb9bda592ae05dd6a373a3e01a5cc7e9

**Comment by rofinn** [comment]
Confirmed that solves the issue on my end as well. Thanks!
