### ISSUE TITLE
SQS.get_queue_url returns dictionary rather than string

### ISSUE THREAD

**Issue by xiuliren** [JuliaCloud/AWSSDK.jl#6]
it is not consistent with the documentation.

```julia
queueUrl = SQS.get_queue_url(QueueName="skeleton")
@show queueUrl
```

**Comment by samoconnor** [comment]
The doc says that the return value is a `GetQueueUrlResult`.
https://github.com/JuliaCloud/AWSSDK.jl/blob/04885675c9b6feeb9b4557b3ae1b1c36964bc522/src/SQS.jl#L634-L643
The example on the linked page is
```
<GetQueueUrlResult>
        <QueueUrl>
            http://sqs.us-east-2.amazonaws.com/123456789012/testQueue
        </QueueUrl>
    </GetQueueUrlResult>
```

So I think it is expected for `GetQueueUrlResult` to have a field called `QueueUrl` that contains the URL string.
```julia
julia> using AWSCore.Services.sqs
julia> sqs("GetQueueUrl", QueueName = "test-q")
DataStructures.OrderedDict{String,Any} with 1 entry:
  "QueueUrl" => "https://sqs.ap-southeast-2.amazonaws.com/551613799374/test-q"

julia> sqs("GetQueueUrl", QueueName = "test-q")["QueueUrl"]
"https://sqs.ap-southeast-2.amazonaws.com/551613799374/test-q"
```

Keep in mind that the documentation is generated from https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.normal.json.
I note that this line: https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.normal.json#L141
says that `GetQueueUrlResult` is a `resultWrapper`. Perhaps we could use that metadata to generate code to automatically unwrap the `QueueUrl`. I'm not sure if this pattern would work in general...

**Comment by samoconnor** [comment]
The output for `SendMessageBatch` specifies [`"resultWrapper":"SendMessageBatchResult"`](
https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.normal.json#L254), but that shape has [more than one member](https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.normal.json#L1205), so it looks like we can't simply unwrap a single member from these shapes.

**Comment by samoconnor** [comment]
Note also that returning a `Dict` with a `QueueUrl` key is consistent with boto3 where the [output is specified](http://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.Client.get_queue_url) as
```
{
    'QueueUrl': 'string'
}
```
