### ISSUE TITLE
documentation of CloudWatch is missing

### ISSUE THREAD

**Issue by xiuliren** [JuliaCloud/AWSSDK.jl#7]
previously, the documentation was there. Now, I can not find it in the documentation place.
https://juliacloud.github.io/AWSCore.jl/build/search.html?q=CloudWatch

**Comment by samoconnor** [comment]
It looks like a Documenter.jl bug is crashing the search function: https://github.com/JuliaDocs/Documenter.jl/issues/639

The doc is still there, it just isn't findable by searching: https://juliacloud.github.io/AWSCore.jl/build/AWSSDK.CloudWatch.html

**Comment by samoconnor** [comment]
I've patched the search_index.js by hand: https://juliacloud.github.io/AWSCore.jl/build/search.html?q=cloudwatch

**Comment by xiuliren** [comment]
thanks, I see. but it is still missing in the left content list.

**Comment by samoconnor** [comment]
refreshing the doc just now "AWSSDK.CloudWatch.jl" is listed at the left.

**Comment by xiuliren** [comment]
It does not show up for me... Could be some caching thing?
